# Generated by Django 3.0.2 on 2020-02-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_product_order'),
        ('account', '0005_remove_user_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wishlist',
            field=models.ManyToManyField(to='product.Product'),
        ),
    ]
