# Generated by Django 3.0.2 on 2020-01-31 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=555)),
                ('base_price', models.PositiveIntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('in_stock', models.IntegerField(default=1)),
                ('main_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('sub_img1', models.ImageField(blank=True, null=True, upload_to='')),
                ('sub_img2', models.ImageField(blank=True, null=True, upload_to='')),
                ('sub_img3', models.ImageField(blank=True, null=True, upload_to='')),
                ('sub_img4', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
