# Generated by Django 3.0.2 on 2020-02-08 17:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0004_remove_order_products'),
        ('product', '0005_remove_product_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='orders',
            field=models.ManyToManyField(to='order.Order'),
        ),
        migrations.AddField(
            model_name='product',
            name='wishlist',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
