# Generated by Django 3.0.2 on 2020-02-08 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200208_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wishlist',
        ),
    ]
