# Generated by Django 3.0.2 on 2020-02-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_products'),
        ('account', '0008_user_wishlist'),
        ('product', '0008_remove_product_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_tags',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='target_sex',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
