# Generated by Django 3.0.2 on 2020-01-26 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=555)),
                ('price', models.PositiveIntegerField()),
                ('discount_price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.Product')),
                ('target_sex', models.CharField(max_length=2)),
                ('sizes', models.CharField(max_length=255)),
                ('is_available', models.BooleanField(default=False)),
            ],
            bases=('product.product',),
        ),
    ]
