# Generated by Django 3.0.2 on 2020-02-06 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200205_0446'),
        ('product', '0003_product_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='order',
        ),
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.ManyToManyField(blank=True, null=True, to='account.order.Order'),
        ),
    ]
