# Generated by Django 3.0.2 on 2020-01-28 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='description',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
    ]
