# Generated by Django 3.0.2 on 2020-01-28 18:35

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200128_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.upload_status_image),
        ),
        migrations.AlterField(
            model_name='blog',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.upload_status_image),
        ),
        migrations.AlterField(
            model_name='blog',
            name='main_img',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.upload_status_image),
        ),
    ]
