# Generated by Django 3.0.2 on 2020-02-08 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wish_list', '0002_auto_20200206_0448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='items',
            new_name='products',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
    ]
