# Generated by Django 3.0.2 on 2020-02-05 04:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_product_final_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_purchased', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Progress', 'In Progress'), ('Canceled', 'Canceled'), ('Delayed', 'Delayed'), ('Delivered', 'Delivered')], default='In Progress', max_length=255)),
                ('total_price', models.PositiveIntegerField(blank=True, null=True)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ordered_products', to='apps.product.Product')),
            ],
        ),
    ]
