# Generated by Django 3.0.2 on 2020-02-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20200208_1749'),
        ('order', '0004_remove_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='product.Product'),
        ),
    ]
