# Generated by Django 3.0.2 on 2020-02-08 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wishlist',
        ),
    ]
