# Generated by Django 3.0.2 on 2020-02-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20200208_1749'),
        ('account', '0007_remove_user_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wishlist',
            field=models.ManyToManyField(to='apps.product.Product'),
        ),
    ]
