# Generated by Django 3.0.2 on 2020-02-10 08:01

import apps.support_ticket.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='description',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=apps.support_ticket.models.upload_ticket_image),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('closed', 'Closed')], default=('closed', 'Closed'), max_length=255, null=True),
        ),
    ]
